import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "./components/Navbar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className="bg-blue-100"
      >
        <NavBar />

        <div className="flex flex-col items-center justify-center p-6">
          {children}
          </div>
      </body>
    </html>
  );
}
